### ISSUE TITLE
Allow using local installed version of testcafe

### ISSUE THREAD

**Issue by btkostner** [DevExpress/testcafe-action#13]
It would be nice if we could skip the installing of testcafe, and defer to the version already installed. Something like this:

```yaml
  Test_Browser:
    name: Test (${{ matrix.browser }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        browser:
          - chrome:headless
          - firefox:headless
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Test
        uses: DevExpress/testcafe-action@latest
        with:
          args: "${{ matrix.browser }} tests"
```

```json
{
  "devDependencies": {
    "testcafe": "^1.8.2",
  }
}
```
