### ISSUE TITLE
Allow to install testcafe addons

### ISSUE THREAD

**Issue by thomaschaaf** [DevExpress/testcafe-action#14]
I need `testcafe-react-selectors` in my project. What would be the best way to install this?

**Comment by wentwrong** [comment]
Hello, @thomaschaaf,

 

TestCafe action able to pick up addon installed locally in your project.
You can add `testcafe-react-selectors` package as a dependency to your package.json file. After that, add `npm i` command in your workflow before running the action:
```yaml
...
- run: npm i
- name: Run TestCafe Tests
  uses: DevExpress/testcafe-action@latest
...
```
