### ISSUE TITLE
skip-install does not seem to work

### ISSUE THREAD

**Issue by Asuza** [DevExpress/testcafe-action#23]
Here is my testcafe-action config (inside the `steps:` block)
```
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
          version: "1.10"
          skip-install: true
          args: "chrome client/tc/Tests/**/*.test.ts --concurrency 2 --config-file .testcaferc.json"
```
However, when the action actually runs, I receive this warning:
```
 Warning: Unexpected input(s) 'skip-install', valid inputs are ['version', 'branch', 'commit', 'args']
```

Am I doing something incorrectly here?
