### ISSUE TITLE
skip-install doesn't appear to work with Yarn PnP

### ISSUE THREAD

**Issue by Asuza** [DevExpress/testcafe-action#26]
Even though I am trying to skip the install (because it's already local to the project), it appears that testcafe-action is still spending almost 30 seconds installing packages via `npx`.

```
Run DevExpress/testcafe-action@latest
  with:
    skip-install: true
    args: chrome client/tc/Tests/**/*.test.ts –-quarantine-mode --concurrency 2 --quarantine-mode attemptLimit=3,successThreshold=1 --ts-config-path ./client/tc/tsconfig.json
    version: latest
VERSION: latest
BRANCH: not specified
COMMIT: not specified
SKIP INSTALL: true
Running TestCafe...
npx: installed 462 in 27.985s
```

Is there anything I can do to get testcafe-action to work with a Yarn PnP repository?
