### ISSUE TITLE
sh: 1: testcafe: not found

### ISSUE THREAD

**Issue by Asuza** [DevExpress/testcafe-action#32]
For reasons I don't understand, testcafe-action no longer finds testcafe. This happens whether I use `skip-install` or not, and even happens when I force testcafe to install via the following:
```yaml
      - name: Force install TestCafe
        run: yarn add testcafe@2.3.0
```

This is running on ubuntu-latest.

Here is the GitHub Action log:
```Run DevExpress/testcafe-action@v0.0.6
  with:
    skip-install: true
    args: chrome client/tc/Tests/**/*.test.ts --concurrency 2 --quarantine-mode attemptLimit=3,successThreshold=1 --ts-config-path ./client/tc/tsconfig.json -s takeOnFails=true
    version: latest
  env:
    NODE_VERSION: 18.14.1
VERSION: latest
BRANCH: not specified
COMMIT: not specified
SKIP INSTALL: true
Running TestCafe...
sh: 1: testcafe: not found
node:child_process:902
    throw err;
    ^

Error: Command failed: xvfb-run --server-args="-screen 0 1280x720x24" npx testcafe chrome client/tc/Tests/**/*.test.ts --concurrency 2 --quarantine-mode attemptLimit=3,successThreshold=1 --ts-config-path ./client/tc/tsconfig.json -s takeOnFails=true
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at Object.<anonymous> (/home/runner/work/_actions/DevExpress/testcafe-action/v0.0.6/index.js:64:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 2018,
  stdout: null,
  stderr: null
}
```

Is this action incompatible with Node.js 18.14.1?

**Comment by AlexKamaev** [comment]
The cause of the issue is unclear. I tested the TestCafe Action with the following workflow, and it works as expected:

```
# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: node version
        run: node -v
      - name: Run TestCafe
        uses: DevExpress/testcafe-action@v0.0.6
        with:
          args: chrome issues/test.js
```

Could you check my example? Does your `yml` file have some significant differences to mine?

**Comment by Asuza** [comment]
After you responded, I noticed some errors earlier in my process that had to be addressed before I could answer. They counted as passing steps even though they weren't.

Here is the majority of my `yml` file, minus sensitive/post bits:
```yaml
name: UI Testing

on:
  pull_request:
    branches:
      - master
    paths:
      - 'client/**'

jobs:
  component_tests:
    name: Component Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read Node.js version to install from `.node-version`
        run: echo "NODE_JS_VERSION=$(cat .node-version)" >> $GITHUB_ENV
        id: read-node-version

      - name: Install required Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.read-node-version.outputs.NODE_JS_VERSION }}"
          cache: 'yarn'

      - name: Install modules
        run: yarn

      - name: Run linter
        run: yarn run lint:testcafe

      - name: Print TestCafe node-version
        run: yarn run testcafe --version

      - name: Run tests
        uses: DevExpress/testcafe-action@v0.0.6
        with:
          skip-install: true
          args: "chrome client/tc/Tests/**/*.test.ts --app 'yarn run start-test-server' --app-init-delay 60000 --concurrency 2 --quarantine-mode attemptLimit=3,successThreshold=1 --ts-config-path ./client/tc/tsconfig.json -s takeOnFails=true"
```

The result of the final two steps are:
```
Run yarn run testcafe --version
2.3.0
```

```
Run DevExpress/testcafe-action@v0.0.6
  with:
    skip-install: true
    args: chrome client/tc/Tests/**/*.test.ts --app 'yarn run start-test-server' --app-init-delay 60000 --concurrency 2 --quarantine-mode attemptLimit=3,successThreshold=1 --ts-config-path ./client/tc/tsconfig.json -s takeOnFails=true
    version: latest
  env:
    NODE_JS_VERSION: 18.14.1
VERSION: latest
BRANCH: not specified
COMMIT: not specified
SKIP INSTALL: true
Running TestCafe...
sh: 1: testcafe: not found
node:child_process:902
    throw err;
    ^

Error: Command failed: xvfb-run --server-args="-screen 0 1280x720x24" npx testcafe chrome client/tc/Tests/**/*.test.ts --app 'yarn run start-test-server' --app-init-delay 60000 --concurrency 2 --quarantine-mode attemptLimit=3,successThreshold=1 --ts-config-path ./client/tc/tsconfig.json -s takeOnFails=true
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at Object.<anonymous> (/home/runner/work/_actions/DevExpress/testcafe-action/v0.0.6/index.js:64:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 1855,
  stdout: null,
  stderr: null
}
```
The value of `start-test-server` is `vue-cli-service serve --mode production --port 8081`.
